Major overhaul and switch to git

diff --git a/build-asterisk b/build-asterisk
--- a/build-asterisk
+++ b/build-asterisk
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -ex
 # Build asterisk (download, compile, install) with many options
 # Usage: build-asterisk {version} {svn-revision}
 # Options:
@@ -11,9 +11,17 @@
 # If not supplied with a version a list is given to choose from
 # If not provided an svn-revsion the latest is used
 
-[ -f /etc/redhat-release ] && [ ! -f /etc/yum.repos.d/epel.repo ] && echo "WARNING: epel required for libjansson" && yum-epel
-install-packages dmidecode subversion gcc-c++/gcc-4.4 ncurses-devel/libncurses-dev libxml2-devel/libxml2-dev make wget openssl-devel/libcurl4-openssl-dev newt-devel/libnewt-dev kernel-devel/ sqlite-devel/libsqlite-dev libuuid-devel/uuid-dev gtk2-devel/libgtk2.0-dev jansson-devel/libjansson-dev binutils-devel/binutils-dev /pkg-config patch avahi-devel unixODBC-devel libtool-ltdl-devel libvorbis-devel libogg-devel libcurl-devel openssl-devel iksemel-devel libsrtp-devel gsm-devel speex-devel
-[ ! -f /usr/lib/libpjsip.so -a ! -f /usr/lib64/libpjsip.so ] && install-pjsip
+dash_usage() # build-asterisk -opts (branch)
+{
+	echo "Cookie"
+}
+
+install_asterisk_dependencies()
+{
+	[ -f /etc/redhat-release ] && [ ! -f /etc/yum.repos.d/epel.repo ] && echo "WARNING: epel required for libjansson" && yum-epel
+	install-packages dmidecode subversion gcc-c++/gcc-4.4 ncurses-devel/libncurses-dev libxml2-devel/libxml2-dev make wget openssl-devel/libcurl4-openssl-dev newt-devel/libnewt-dev kernel-devel/ sqlite-devel/libsqlite-dev libuuid-devel/uuid-dev gtk2-devel/libgtk2.0-dev jansson-devel/libjansson-dev binutils-devel/binutils-dev /pkg-config patch avahi-devel unixODBC-devel libtool-ltdl-devel libvorbis-devel libogg-devel libcurl-devel openssl-devel iksemel-devel libsrtp-devel gsm-devel speex-devel net-tools avahi nss-mdns
+	[ ! -f /usr/lib/libpjsip.so -a ! -f /usr/lib64/libpjsip.so ] && install-pjsip
+}
 
 install_tls()
 {
@@ -51,6 +59,20 @@ configure_menuselect()
 	menuselect/menuselect $REF_DEBUG $BUILD_NATIVE --enable DONT_OPTIMIZE --enable TEST_FRAMEWORK --enable DO_CRASH --enable BETTER_BACKTRACES --enable EXTRA-SOUNDS-EN-GSM menuselect.makeopts
 }
 
+check_virtual()
+{
+	# in virtualized environments, native build can result in illegal instructions
+	SYSTEM_PRODUCT_NAME="`cat /sys/devices/virtual/dmi/id/product_name`"
+	if [ "$SYSTEM_PRODUCT_NAME" = "" ]
+	then
+		# to be safe, disable if unknown
+		disable_menuselect BUILD_NATIVE
+	elif [ "$SYSTEM_PRODUCT_NAME" = "VMware Virtual Platform" ]
+	then
+		disable_menuselect BUILD_NATIVE
+	fi
+}
+
 install_testsuite_dependencies()
 {
 	# make sure dependencies are installed
@@ -70,6 +92,304 @@ install_testsuite_dependencies()
 	fi
 
 }
+
+dash_h() # Help
+{
+	sed -n '/^dash.*/ s/dash_\([^(]*\).*# *\(.*\)/\1 - \2/p' < $0
+}
+
+list_asterisk_branches()
+{
+	if [ "$1" == "certified" -o "$BRANCH_PREFIX" = "certified" ]
+	then
+		git ls-remote -h $GIT_REPO | sed 's|.*refs/heads/||' | grep '^certified/'
+	elif [ "$1" == "team" ]
+	then
+		git ls-remote -h $GIT_REPO | sed 's|.*refs/heads/||' | grep '^team/'
+	else
+		git ls-remote -h $GIT_REPO | sed 's|.*refs/heads/||' | grep -v '^team/' | grep -v '^certified/'
+	fi
+}
+dash_b() # List Asterisk Branches
+{
+	list_asterisk_branches $*
+	exit 0
+}
+
+dash_z() # Use internal repo (digium only)
+{
+	GIT_REPO="http://gerrit.digium.internal/r/asterisk"
+}
+
+dash_g() # Use github repo (readonly)
+{
+	GIT_REPO="https://github.com/asterisk/asterisk"
+}
+
+enable_commit_hook()
+{
+	echo "Don't know how to enable commit hook yet"
+}
+
+dash_d() # Developer Mode (DONT_OPTIMIZE, BETTER_BACKTRACES, DO_CRASH, TEST_FRAMEWORK, commit hook)
+{
+	CONFIG_PARAMS="$CONFIG_PARAMS --enable-dev-mode"
+	enable_menuselect DONT_OPTIMIZE
+	enable_menuselect BETTER_BACKTRACES
+	enable_menuselect DO_CRASH
+	enable_menuselect TEST_FRAMEWORK
+	enable_commit_hook
+}
+
+dash_ref() # Enable REF_DEBUG
+{
+	enable_menuselect REF_DEBUG
+}
+
+dash_i() # install asterisk
+{
+	INSTALL="y"
+}
+
+dash_n() # don't install asterisk
+{
+	INSTALL="n"
+}
+
+dash_c() # use the certified branch
+{
+	BRANCH_PREFIX="certified"
+}
+
+dash_test()
+{
+	echo "This is the test option: $*"
+	DO_THIS="do_test"
+	return 1
+}
+
+do_test()
+{
+	echo "Test process started"
+}
+
+check_asterisk()
+{
+	if [ -f Makefile && -f ./configure ]
+	then
+		MAKEFILE=$(head -2 Makefile | fgrep Asterisk)
+		if [ ! -z "$MAKEFILE" ]
+		then
+			return
+		fi
+	fi
+	echo "ERROR: the current directory does not contain Asterisk source code"
+}
+
+run_configure()
+{
+	echo "CONFIGURE $CONFIG_PARAMS"
+	./configure $CONFIG_PARAMS
+}
+
+set_menuselect()
+{
+	echo "MENUSELECT $MENUSELECT"
+	make menuselect.makeopts
+	menuselect/menuselect $MENUSELECT
+}
+
+dash_remenu() # make distclean, configure normally, but stop at menuselect
+{
+	check_asterisk
+	make clean
+	make distclean
+	run_configure
+	set_menuselect
+	# and leave user in the menuselect menu
+	make menuselect
+	exit 0
+}
+
+dash_rebuild() # make distclean and recompile normally
+{
+	check_asterisk
+	make clean
+	make distclean
+	run_configure
+	set_menuselect
+	compile_asterisk
+	exit 0
+}
+
+dash_vgr() # run asterisk under valgrind
+{
+	check_asterisk
+	sudo valgrind -q --log-file=/tmp/vg.log --num-callers=50 --error-limit=no --leak-check=no --undef-value-errors=no --suppressions=contrib/valgrind.supp asterisk -c $*
+	exit 0
+}
+
+dash_tls() # install TLS support
+{
+	check_asterisk
+	[ `whoami` != 'root' ] && exec sudo env PATH=$PATH $0 -tls
+	install_tls
+	exit 0
+}
+
+enable_menuselect()
+{
+	MENUSELECT="$MENUSELECT --enable $1"
+}
+
+disable_menuselect()
+{
+	MENUSELECT="$MENUSELECT --disable $1"
+}
+
+check_install()
+{
+    while [ "$INSTALL" != "y" -a "$INSTALL" != "n" ]
+    do
+		echo -n "Install (y/n): "
+		read INSTALL
+    done
+
+	if [ "$INSTALL" = "y" ]
+	then
+		install_asterisk
+	fi
+}
+
+git_head_from_branch()
+{
+	MATCH="refs/heads/$1\$"
+	HEAD=$(git ls-remote -h $GIT_REPO |grep $MATCH |cut -d $'\t' -f 1)
+}
+
+git_asterisk()
+{
+	BRANCH="$1"
+	if [ ! -z "$BRANCH_PREFIX" ]
+	then
+		BRANCH="$BRANCH_PREFIX/$BRANCH"
+	fi
+
+	git_head_from_branch $BRANCH
+
+	if [ -z "$HEAD" ]
+	then
+		echo "ERROR: Unable to locate branch $BRANCH at $GIT_REPO"
+		exit 1
+	fi
+
+	DEST_PATH="$(echo "$BRANCH" |tr '/' '-')-$HEAD"
+
+	if [ -e "$DEST_PATH" ]
+	then
+		echo "ERROR: $DEST_PATH already exists - aborting"
+		exit 1
+	fi
+
+	if [ -d "$CACHE_DIR/$DEST_PATH" ]
+	then
+		# get it from cache
+		mkdir "$DEST_PATH"
+		rsync -avr "$CACHE_DIR/$DEST_PATH/." "$DEST_PATH/."
+	else
+		git clone $GIT_REPO --branch $BRANCH $DEST_PATH
+	fi
+
+	if [ ! -d "$CACHE_DIR/$DEST_PATH" ]
+	then
+		# make a copy in the cache
+		mkdir -p "$CACHE_DIR/$DEST_PATH"
+		rsync -avrq "$DEST_PATH/." "$CACHE_DIR/$DEST_PATH/."
+	fi
+
+	cd $DEST_PATH
+
+}
+
+compile_asterisk()
+{
+	make -j$(nproc)
+}
+
+install_asterisk()
+{
+	sudo make install
+}
+
+main()
+{
+	DO_THIS=""
+	CACHE_DIR="/tmp/build-asterisk-cache"
+	INSTALL="prompt"
+	MENUSELECT="--enable EXTRA-SOUNDS-EN-GSM"
+	GIT_REPO="http://gerrit.asterisk.org/asterisk"
+	BRANCH_PREFIX=""
+
+	check_libdir
+	CONFIG_PARAMS=" --libdir=$LIBDIR"
+
+	check_virtual
+
+	while [ "${1:0:1}" = "-" ]
+	do
+		OPT="${1:1}"
+		shift
+		if type -t "dash_${OPT}" >/dev/null
+		then
+			dash_${OPT} $*
+			shift $?
+			continue
+		fi
+		# try individual letters
+		for OPT1 in $(echo "$OPT" | fold -w1)
+		do
+			if type -t "dash_$OPT1" > /dev/null
+			then
+				dash_$OPT1 $*
+				shift $?
+			else
+				echo "Option does not exist: $OPT1"
+				exit 1
+			fi
+		done
+	done
+
+	echo "MENUSELECT=$MENUSELECT"
+	echo "INSTALL=$INSTALL"
+
+	if [ ! -z "$DO_THIS" ]
+	then
+		$DO_THIS $*
+		exit $?
+	fi
+
+	if [ -z "$1" ]
+	then
+		echo "Exiting with nothing to do"
+		exit 1
+	fi
+
+	git_asterisk $*
+	run_configure
+	set_menuselect
+	compile_asterisk
+	check_install
+	echo "Success" && exit 0
+}
+
+check_libdir()
+{
+	LIBDIR="/usr/lib"
+	[ `uname -m` = "x86_64" ] && [ -d /usr/lib64 ] && LIBDIR="/usr/lib64"
+}
+
+previous_main()
+{
 
 
 SYSLIBDIR="/usr/lib"
@@ -355,3 +675,6 @@ then
 fi
 
 echo "===> LEAVING BUILD DIRECTORY: `pwd`"
+}
+
+main $*
