Additional git improvements

diff --git a/build-asterisk b/build-asterisk
--- a/build-asterisk
+++ b/build-asterisk
@@ -1,15 +1,5 @@
 #!/bin/bash -ex
 # Build asterisk (download, compile, install) with many options
-# Usage: build-asterisk {version} {svn-revision}
-# Options:
-#	-i = install after build succeds
-#	-i(path) = install to local path (see local-asterisk)
-#	-n = do not install (otherwise it prompts)
-#	-v = build into directory with the version number (no suffix)
-#	-c = use certified branch
-#
-# If not supplied with a version a list is given to choose from
-# If not provided an svn-revsion the latest is used
 
 dash_usage() # build-asterisk -opts (branch)
 {
@@ -18,18 +8,40 @@ dash_usage() # build-asterisk -opts (branch)
 
 install_asterisk_dependencies()
 {
-	[ -f /etc/redhat-release ] && [ ! -f /etc/yum.repos.d/epel.repo ] && echo "WARNING: epel required for libjansson" && yum-epel
+	if [ -f /etc/redhat-release -a ! -f /etc/yum.repos.d/epel.repo ]
+	then
+		echo "WARNING: epel required for libjansson"
+		yum-epel
+	fi
 	install-packages dmidecode subversion gcc-c++/gcc-4.4 ncurses-devel/libncurses-dev libxml2-devel/libxml2-dev make wget openssl-devel/libcurl4-openssl-dev newt-devel/libnewt-dev kernel-devel/ sqlite-devel/libsqlite-dev libuuid-devel/uuid-dev gtk2-devel/libgtk2.0-dev jansson-devel/libjansson-dev binutils-devel/binutils-dev /pkg-config patch avahi-devel unixODBC-devel libtool-ltdl-devel libvorbis-devel libogg-devel libcurl-devel openssl-devel iksemel-devel libsrtp-devel gsm-devel speex-devel net-tools avahi nss-mdns
-	[ ! -f /usr/lib/libpjsip.so -a ! -f /usr/lib64/libpjsip.so ] && install-pjsip
+	if [ ! -f /usr/lib/libpjsip.so -a ! -f /usr/lib64/libpjsip.so ]
+	then
+		install-pjsip
+	fi
 }
 
 install_tls()
 {
-	[ ! -f ./contrib/scripts/ast_tls_cert ] && echo "ERROR: Not in an Asterisk directory" && exit 1
-	[ ! -d /etc/asterisk/keys ] && mkdir /etc/asterisk/keys
+	if [ ! -f ./contrib/scripts/ast_tls_cert ]
+	then
+		echo "ERROR: Not in an Asterisk directory"
+		exit 1
+	fi
+	if [ ! -d /etc/asterisk/keys ]
+	then
+		mkdir /etc/asterisk/keys
+	fi
 	./contrib/scripts/ast_tls_cert -C $HOSTNAME -O "Acme Branch Company" -d /etc/asterisk/keys
-	[ ! -f /etc/asterisk/keys/ca.crt ] && echo "ERROR: ca.crt not found" && exit 1
-	[ ! -f /etc/asterisk/keys/ca.key ] && echo "ERROR: ca.keys not found" && exit 1
+	if [ ! -f /etc/asterisk/keys/ca.crt ]
+	then
+		echo "ERROR: ca.crt not found"
+		exit 1
+	fi
+	if [ ! -f /etc/asterisk/keys/ca.key ]
+	then
+		echo "ERROR: ca.keys not found"
+		exit 1
+	fi
 	./contrib/scripts/ast_tls_cert -m client -c /etc/asterisk/keys/ca.crt -k /etc/asterisk/keys/ca.key -C $HOSTNAME -O "Acme Branch Company" -d /etc/asterisk/keys -o user
 	ls /etc/asterisk/keys
 }
@@ -43,7 +55,7 @@ install_tls()
 # Asterisk 11:
 #   menuselect/menuselect --disable-category MENUSELECT_CORE_SOUNDS --disable-category MENUSELECT_EXTRA_SOUNDS --disable-category MENUSELECT_MOH --enable-category MENUSELECT_ADDONS --enable res_pktccops --enable chan_mgcp --enable chan_motif --enable app_dahdibarge --enable app_meetme --enable app_page --enable res_mwi_blf --enable res_snmp --enable res_srtp --enable DONT_OPTIMIZE --disable BUILD_NATIVE --disable res_calendar --disable res_calendar_caldav --disable res_calendar_ews --disable res_calendar_exchange --disable res_calendar_icalendar #
 #
-configure_menuselect()
+NOT_USED_configure_menuselect()
 {
 	echo "Configuring menuselect options"
 	make menuselect.makeopts
@@ -57,6 +69,15 @@ configure_menuselect()
 	REF_DEBUG=""
 	# REF_DEBUG="--enable REF_DEBUG"
 	menuselect/menuselect $REF_DEBUG $BUILD_NATIVE --enable DONT_OPTIMIZE --enable TEST_FRAMEWORK --enable DO_CRASH --enable BETTER_BACKTRACES --enable EXTRA-SOUNDS-EN-GSM menuselect.makeopts
+}
+
+check_libdir()
+{
+	LIBDIR="/usr/lib"
+	if [ `uname -m` = "x86_64" -a -d /usr/lib64 ]
+	then
+		LIBDIR="/usr/lib64"
+	fi
 }
 
 check_virtual()
@@ -78,15 +99,24 @@ install_testsuite_dependencies()
 	# make sure dependencies are installed
 	# this is run from testsuite root, giving access to contents
 	install-packages python-pip python-setuptools PyYAML python-twisted-core lua-devel gdb
-	[ ! -d /usr/lib/python2.?/site-packages/construct ] && sudo pip install construct
-	[ ! -d /usr/lib/python2.?/site-packages/requests ] && sudo pip install requests
-	[ ! -d /usr/lib/python2.?/site-packages/autobahn ] && sudo pip install autobahn
+	if [ ! -d /usr/lib/python2.?/site-packages/construct ]
+	then
+		sudo pip install construct
+	fi
+	if [ ! -d /usr/lib/python2.?/site-packages/requests ]
+	then
+		sudo pip install requests
+	fi
+	if [ ! -d /usr/lib/python2.?/site-packages/autobahn ]
+	then
+		sudo pip install autobahn
+	fi
 	which sipp > /dev/null || install-sipp
 	which pjsua > /dev/null || install-pjsua
 
 	which asttest || (cd asttest ; make ; sudo make install ; cp /usr/local/bin/asttest /usr/bin)
 
-	if [ -z "`pip list |fgrep starpy`" ] 
+	if [ -z "`pip list |fgrep starpy`" ]
 	then
 		(cd addons && make update && cd starpy && sudo python setup.py install)
 	fi
@@ -95,19 +125,21 @@ install_testsuite_dependencies()
 
 dash_h() # Help
 {
-	sed -n '/^dash.*/ s/dash_\([^(]*\).*# *\(.*\)/\1 - \2/p' < $0
+	sed -n '/^dash_.*/ s/dash_\([^(]*\).*# *\(.*\)/\1 - \2/p' < $0
 }
 
 list_asterisk_branches()
 {
+	select_repo
+
 	if [ "$1" == "certified" -o "$BRANCH_PREFIX" = "certified" ]
 	then
-		git ls-remote -h $GIT_REPO | sed 's|.*refs/heads/||' | grep '^certified/'
+		git ls-remote -h $GIT_URL | sed 's|.*refs/heads/||' | grep '^certified/'
 	elif [ "$1" == "team" ]
 	then
-		git ls-remote -h $GIT_REPO | sed 's|.*refs/heads/||' | grep '^team/'
+		git ls-remote -h $GIT_URL | sed 's|.*refs/heads/||' | grep '^team/'
 	else
-		git ls-remote -h $GIT_REPO | sed 's|.*refs/heads/||' | grep -v '^team/' | grep -v '^certified/'
+		git ls-remote -h $GIT_URL | sed 's|.*refs/heads/||' | grep -v '^team/' | grep -v '^certified/'
 	fi
 }
 dash_b() # List Asterisk Branches
@@ -116,31 +148,29 @@ dash_b() # List Asterisk Branches
 	exit 0
 }
 
-dash_z() # Use internal repo (digium only)
+dash_l() # Use internal repo (digium only)
 {
-	GIT_REPO="https://gerrit.digium.internal/r/asterisk"
+	USE_INTERNAL="y"
 }
 
 dash_g() # Use github repo (readonly)
 {
-	GIT_REPO="https://github.com/asterisk/asterisk"
+	USE_GITHUB="y"
 }
 
-enable_commit_hook()
+dash_m() # Install commit hook
 {
-	echo "Don't know how to enable commit hook yet"
-	GIT_REPO="https://$USER@gerrit.asterisk.org/asterisk"
-	GIT_COMMIT_HOOK="scp -p -P 29418 $USER@gerrit.asterisk.org:hooks/commit-msg .git/hooks/"
+	COMMIT_HOOK="y"
 }
 
-dash_d() # Developer Mode (DONT_OPTIMIZE, BETTER_BACKTRACES, DO_CRASH, TEST_FRAMEWORK, commit hook)
+dash_d() # Developer Mode (DONT_OPTIMIZE, BETTER_BACKTRACES, DO_CRASH, TEST_FRAMEWORK)
 {
+	DEV_MODE="y"
 	CONFIG_PARAMS="$CONFIG_PARAMS --enable-dev-mode"
 	enable_menuselect DONT_OPTIMIZE
 	enable_menuselect BETTER_BACKTRACES
 	enable_menuselect DO_CRASH
 	enable_menuselect TEST_FRAMEWORK
-	enable_commit_hook
 }
 
 dash_ref() # Enable REF_DEBUG
@@ -234,7 +264,10 @@ dash_vgr() # run asterisk under valgrind
 dash_tls() # install TLS support
 {
 	check_asterisk
-	[ `whoami` != 'root' ] && exec sudo env PATH=$PATH $0 -tls
+	if [ `whoami` != 'root' ]
+	then
+		exec sudo env PATH=$PATH $0 -tls
+	fi
 	install_tls
 	exit 0
 }
@@ -266,11 +299,13 @@ check_install()
 git_head_from_branch()
 {
 	MATCH="refs/heads/$1\$"
-	HEAD=$(git ls-remote -h $GIT_REPO |grep $MATCH |cut -d $'\t' -f 1)
+	HEAD=$(git ls-remote -h $GIT_URL |grep $MATCH |cut -d $'\t' -f 1)
 }
 
 git_asterisk()
 {
+	select_repo
+
 	BRANCH="$1"
 	if [ ! -z "$BRANCH_PREFIX" ]
 	then
@@ -281,11 +316,15 @@ git_asterisk()
 
 	if [ -z "$HEAD" ]
 	then
-		echo "ERROR: Unable to locate branch $BRANCH at $GIT_REPO"
+		echo "ERROR: Unable to locate branch $BRANCH at $GIT_URL"
 		exit 1
 	fi
 
 	DEST_PATH="$(echo "$BRANCH" |tr '/' '-')-$HEAD"
+	if [ "$TEST_SUITE" = "y" ]
+	then
+		DEST_PATH="testsuite-$DEST_PATH"
+	fi
 
 	if [ -e "$DEST_PATH" ]
 	then
@@ -299,7 +338,7 @@ git_asterisk()
 		mkdir "$DEST_PATH"
 		rsync -avr "$CACHE_DIR/$DEST_PATH/." "$DEST_PATH/."
 	else
-		git clone $GIT_REPO --branch $BRANCH $DEST_PATH
+		git clone $GIT_URL --branch $BRANCH $DEST_PATH
 	fi
 
 	if [ ! -d "$CACHE_DIR/$DEST_PATH" ]
@@ -311,8 +350,13 @@ git_asterisk()
 
 	cd $DEST_PATH
 
-	if [ ! -z "$GIT_COMMIT_HOOK" ]
+	if [ "$COMMIT_HOOK" = "y" ]
 	then
+		if [ -z "$GIT_COMMIT_HOOK" ]
+		then
+			echo "ERROR: GIT_COMMIT_HOOK not set"
+			exit 1
+		fi
 		$GIT_COMMIT_HOOK
 	fi
 
@@ -325,23 +369,87 @@ compile_asterisk()
 
 install_asterisk()
 {
-	sudo make install
+	# wait less than silently if programmer is afk...
+	while ! sudo make uninstall ; do echo -en '\007'; done
+	while ! sudo make install ; do echo -en '\007'; done
+
+	# install samples if missing
+	sudo /bin/bash -c '[ ! -f /etc/asterisk/asterisk.conf ] && make samples'
+
+	# fixup asterisk.conf - it may have the wrong path
+	if [ "$LIBDIR" = "/usr/lib64" ] 
+	then
+		sudo sed -i '/^astmoddir/ s|/usr/lib/|/usr/lib64/|' /etc/asterisk/asterisk.conf
+	else
+		sudo sed -i '/^astmoddir/ s|/usr/lib64/|/usr/lib/|' /etc/asterisk/asterisk.conf
+	fi
+}
+
+dash_t() # Get the Testsuite instead of Asterisk
+{
+	TEST_SUITE="y"
+}
+
+select_repo()
+{
+	GIT_USER=""
+	if [ "$COMMIT_HOOK" = "y" ]
+	then
+		GIT_USER="$USER@"
+	fi
+
+	if [ "$USE_GITHUB" = "y" ]
+	then
+		GIT_PROTO="https://"
+		GIT_SERVER="github.com"
+		GIT_PATH="/asterisk"
+	elif [ "$USE_INTERNAL" = "y" ]
+	then
+		GIT_PROTO="http://"
+		GIT_SERVER="gerrit.digium.internal"
+		GIT_PATH="/r"
+	else
+		GIT_PROTO="https://"
+		GIT_SERVER="gerrit.asterisk.org"
+		GIT_PATH=""
+	fi
+
+	if [ "$TEST_SUITE" = "y" ]
+	then
+		GIT_REPO="testsuite"
+	else
+		GIT_REPO="asterisk"
+	fi
+
+	GIT_URL="${GIT_PROTO}${GIT_USER}${GIT_SERVER}${GIT_PATH}/${GIT_REPO}"
+	if [ "$COMMIT_HOOK" = "y" ]
+	then
+		GIT_COMMIT_HOOK="scp -p -P 29418 ${GITUSER}${GIT_SERVER}:hooks/commit-msg .git/hooks/"
+	fi
 }
 
 main()
 {
 	DO_THIS=""
-	CACHE_DIR="/tmp/build-asterisk-cache"
+	CACHE_DIR="$HOME/.build-asterisk-cache"
 	INSTALL="prompt"
 	MENUSELECT="--enable EXTRA-SOUNDS-EN-GSM"
-	GIT_REPO="https://gerrit.asterisk.org/asterisk"
+	GIT_URL="-not-set-"
+	GIT_COMMIT_HOOK=""
 	BRANCH_PREFIX=""
+	DEST_PATH=""
+	DEV_MODE="n"
+	TEST_SUITE="n"
+	USE_GITHUB="n"
+	USE_INTERNAL="n"
+	COMMIT_HOOK="n"
 
 	check_libdir
 	CONFIG_PARAMS=" --libdir=$LIBDIR"
 
 	check_virtual
 
+	# parse dash options
 	while [ "${1:0:1}" = "-" ]
 	do
 		OPT="${1:1}"
@@ -353,21 +461,18 @@ main()
 			continue
 		fi
 		# try individual letters
-		for OPT1 in $(echo "$OPT" | fold -w1)
+		for SINGLE in $(echo "$OPT" | fold -w1)
 		do
-			if type -t "dash_$OPT1" > /dev/null
+			if type -t "dash_$SINGLE" > /dev/null
 			then
-				dash_$OPT1 $*
+				dash_$SINGLE $*
 				shift $?
 			else
-				echo "Option does not exist: $OPT1"
+				echo "Option does not exist: $SINGLE"
 				exit 1
 			fi
 		done
 	done
-
-	echo "MENUSELECT=$MENUSELECT"
-	echo "INSTALL=$INSTALL"
 
 	if [ ! -z "$DO_THIS" ]
 	then
@@ -381,18 +486,27 @@ main()
 		exit 1
 	fi
 
-	git_asterisk $*
+	BRANCH="$1"
+
+	if [ "$1" = "testsuite" ]
+	then
+		TEST_SUITE="y"
+		BRANCH="master"
+	fi
+
+
+	git_asterisk $BRANCH
+	if [ "$TEST_SUITE" = "y" ]
+	then
+		install_testsuite_dependencies
+		exit 0
+	fi
+	install_asterisk_dependencies
 	run_configure
 	set_menuselect
 	compile_asterisk
 	check_install
-	echo "Success" && exit 0
-}
-
-check_libdir()
-{
-	LIBDIR="/usr/lib"
-	[ `uname -m` = "x86_64" ] && [ -d /usr/lib64 ] && LIBDIR="/usr/lib64"
+	echo "Asterisk succesfully built in $DEST_PATH" && exit 0
 }
 
 previous_main()
