Added libjannson

diff --git a/install-testsuite b/install-testsuite
--- a/install-testsuite
+++ b/install-testsuite
@@ -22,15 +22,15 @@ cd testsuite-support
 
 # yappcap Installation
 
-git clone https://github.com/otherwiseguy/yappcap
-[ $? -ne 0 ] && echo "ERROR: git clone yappcap failed" && exit 1
-[ ! -d yappcap ] && echo "ERROR: target directory yappcap missing" && exit 1
-cd yappcap
-make
-[ $? -ne 0 ] && echo "ERROR: make yappcap failed" && exit 1
-sudo make install
-[ $? -ne 0 ] && echo "ERROR: make yappcap install failed" && exit 1
-cd ..
+#git clone https://github.com/otherwiseguy/yappcap
+#[ $? -ne 0 ] && echo "ERROR: git clone yappcap failed" && exit 1
+#[ ! -d yappcap ] && echo "ERROR: target directory yappcap missing" && exit 1
+#cd yappcap
+#make
+#[ $? -ne 0 ] && echo "ERROR: make yappcap failed" && exit 1
+#sudo make install
+#[ $? -ne 0 ] && echo "ERROR: make yappcap install failed" && exit 1
+#cd ..
 
 # SIPp Installation
 
@@ -146,6 +146,18 @@ sudo python setup.py install
 cd ..
 cd ..
 
+# if libjansson not installed...
+if [ ! -f /usr/local/lib/libjansson.so.4 ]
+then
+	wget -O /tmp/jansson-2.4.tar.gz http://www.digip.org/jansson/releases/jansson-2.4.tar.gz
+	tar xvfz /tmp/jansson-2.4.tar.gz --no-same-owner
+	(cd jansson-2.4; ./configure && make && sudo make install)
+fi
+
+if [ -d /usr/lib64 ]
+then
+	sudo cp /usr/local/lib/libjansson.so.4 /usr/lib64
+fi
 
 echo ""
 echo "*** Configure asterisk with ./configure --enable-dev-mode and install ***"
