disable pjproject due to duplication

diff --git a/install-testsuite b/install-testsuite
--- a/install-testsuite
+++ b/install-testsuite
@@ -3,6 +3,7 @@
 # need epel for PyYAML
 
 set -x
+[ -f /etc/redhat-release ] && alias apt-get=yum
 
 if [ "$1" = "-u" ]
 then
@@ -37,13 +38,13 @@ fi
 
 
 SYSLIBDIR=/usr/lib
-[ "`uname -m`" = "x86_64" ] && SYSLIBDIR=/usr/lib64
+[ "`uname -m`" = "x86_64" ] && [ -d /usr/lib64 ] && SYSLIBDIR=/usr/lib64
 
 # not centos
-[ ! -f /etc/redhat-release ] && sudo apt-get -y install python2.7-dev libncurses-dev libz-dev libssl-dev libxml2-dev libsqlite3-dev uuid-dev uuid libspeex-dev libspeexdsp-dev libogg-dev libvorbis-dev libasound2-dev portaudio19-dev libcurl4-openssl-dev libpq-dev unixodbc-dev libsqlite0-dev libmysqlclient15-dev libneon27-dev libgmime-2.6-dev libusb-dev liblua5.1-0-dev lua5.1 libopenh323-dev libvpb-dev libgtk2.0-dev libmysqlclient-dev libbluetooth-dev libradiusclient-ng-dev freetds-dev libsnmp-dev libiksemel-dev libcorosync-dev libnewt-dev libpopt-dev libedit-dev doxygen libjansson-dev libldap-dev subversion git libxslt1-dev libpcap0.8-dev libtiff-dev gawk
+[ ! -f /etc/redhat-release ] && sudo apt-get -y install python2.7-dev libncurses-dev libz-dev libssl-dev libxml2-dev libsqlite3-dev uuid-dev uuid libspeex-dev libspeexdsp-dev libogg-dev libvorbis-dev libasound2-dev portaudio19-dev libcurl4-openssl-dev libpq-dev unixodbc-dev libsqlite0-dev libmysqlclient15-dev libneon27-dev libgmime-2.6-dev libusb-dev liblua5.1-0-dev lua5.1 libopenh323-dev libvpb-dev libgtk2.0-dev libmysqlclient-dev libbluetooth-dev libradiusclient-ng-dev freetds-dev libsnmp-dev libiksemel-dev libcorosync-dev libnewt-dev libpopt-dev libedit-dev doxygen libjansson-dev libldap-dev subversion git libxslt1-dev libpcap0.8-dev libtiff-dev gawk python-yaml
 
 # centos
-[ -f /etc/redhat-release ] && sudo apt-get -y install automake PyYAML libpcap-devel gcc-objc python-devel python-twisted git subversion libtiff-devel make wget openssl-devel ncurses-devel newt-devel libxml2-devel kernel-devel gcc gcc-c++ sqlite-devel libuuid-devel gtk2-devel gmime-devel gmime22-devel patch python-setuptools unixODBC-devel libcurl-devel libogg-devel libvorbis-devel speex-devel spandsp-devel freetds-devel net-snmp-devel iksemel-devel openais-devel popt-devel libtool-ltdl-devel libsqlite3x-devel radiusclient-ng-devel portaudio-devel postgresql-devel libresample-devel neon-devel libical-devel openldap-devel sqlite2-devel mysql-devel bluez-libs-devel jack-audio-connection-kit-devel Cython python-pip python-yaml
+[ -f /etc/redhat-release ] && sudo apt-get -y install automake PyYAML libpcap-devel gcc-objc python-devel python-twisted git subversion libtiff-devel make wget openssl-devel ncurses-devel newt-devel libxml2-devel kernel-devel gcc gcc-c++ sqlite-devel libuuid-devel gtk2-devel gmime-devel gmime22-devel patch python-setuptools unixODBC-devel libcurl-devel libogg-devel libvorbis-devel speex-devel spandsp-devel freetds-devel net-snmp-devel iksemel-devel openais-devel popt-devel libtool-ltdl-devel libsqlite3x-devel radiusclient-ng-devel portaudio-devel postgresql-devel libresample-devel neon-devel libical-devel openldap-devel sqlite2-devel mysql-devel bluez-libs-devel jack-audio-connection-kit-devel Cython python-pip python-yaml lua-devel gdb
 
 #testsuite/contrib/scripts/install_prereq install
 
@@ -89,19 +90,20 @@ cd ..
 
 # install PJPROJECT
 
-rm -rf pjproject
-git clone https://github.com/asterisk/pjproject pjproject
-[ $? -ne 0 ] && echo "ERROR: svn co pjproject failed" && exit 1
-cd pjproject
-[ $? -ne 0 ] && echo "ERROR: cd to pjproject failed" && exit 1
-./configure --prefix=/usr --enable-shared --disable-sound --disable-resample --disable-video --disable-opencore-amr --libdir=$SYSLIBDIR
-make dep
-[ $? -ne 0 ] && echo "ERROR: make dep pjproject failed" && exit 1
-make
-[ $? -ne 0 ] && echo "ERROR: make pjproject failed" && exit 1
-sudo make install
-sudo ldconfig
-cd ..
+# this is duplicated later as pointed out by sam
+#rm -rf pjproject
+#git clone https://github.com/asterisk/pjproject pjproject
+#[ $? -ne 0 ] && echo "ERROR: svn co pjproject failed" && exit 1
+#cd pjproject
+#[ $? -ne 0 ] && echo "ERROR: cd to pjproject failed" && exit 1
+#CFLAGS='-DPJ_HAS_IPV6=1' ./configure --prefix=/usr --enable-shared --disable-sound --disable-resample --disable-video --disable-opencore-amr --libdir=$SYSLIBDIR
+#make dep
+#[ $? -ne 0 ] && echo "ERROR: make dep pjproject failed" && exit 1
+#make
+#[ $? -ne 0 ] && echo "ERROR: make pjproject failed" && exit 1
+#sudo make install
+#sudo ldconfig
+#cd ..
 
 # install PJSUA
 
