trying to fix pjsua

diff --git a/install-testsuite b/install-testsuite
--- a/install-testsuite
+++ b/install-testsuite
@@ -2,6 +2,8 @@
 # asterisk testsuite - install needed dependancies
 # need epel for PyYAML
 
+set -x
+
 if [ "$1" = "-u" ]
 then
 	sudo rm -rfv /usr/include/pj*
@@ -43,7 +45,7 @@ SYSLIBDIR=/usr/lib
 
 # assuming CentOS for now
 
-sudo yum -y install automake PyYAML lua-devel libpcap-devel gcc-objc python-devel python-twisted git subversion libtiff-devel make wget openssl-devel ncurses-devel newt-devel libxml2-devel kernel-devel gcc gcc-c++ sqlite-devel libuuid-devel gtk2-devel gmime-devel gmime22-devel patch python-setuptools unixODBC-devel libcurl-devel libogg-devel libvorbis-devel speex-devel spandsp-devel freetds-devel net-snmp-devel iksemel-devel openais-devel popt-devel libtool-ltdl-devel libsqlite3x-devel radiusclient-ng-devel portaudio-devel postgresql-devel libresample-devel neon-devel libical-devel openldap-devel sqlite2-devel mysql-devel bluez-libs-devel jack-audio-connection-kit-devel Cython python-pip
+sudo yum -y install automake PyYAML lua lua-devel libpcap-devel gcc-objc python-devel python-twisted git subversion libtiff-devel make wget openssl-devel ncurses-devel newt-devel libxml2-devel kernel-devel gcc gcc-c++ sqlite-devel libuuid-devel gtk2-devel gmime-devel gmime22-devel patch python-setuptools unixODBC-devel libcurl-devel libogg-devel libvorbis-devel speex-devel spandsp-devel freetds-devel net-snmp-devel iksemel-devel openais-devel popt-devel libtool-ltdl-devel libsqlite3x-devel radiusclient-ng-devel portaudio-devel postgresql-devel libresample-devel neon-devel libical-devel openldap-devel sqlite2-devel mysql-devel bluez-libs-devel jack-audio-connection-kit-devel Cython python-pip python-yaml
 
 #testsuite/contrib/scripts/install_prereq install
 
@@ -77,11 +79,11 @@ SIPP_DIR="sipp-3.3"
 
 rm -rf $SIPP_DIR
 [ $? -ne 0 ] && echo "ERROR: rm -rf $SIPP_DIR failed" && exit 1
-tar xvfz sipp.tgz
+tar xfz sipp.tgz > tar.out
 [ $? -ne 0 ] && echo "ERROR: tar extraction failed" && exit 1
 [ ! -d $SIPP_DIR ] && echo "ERROR: tar extraction target missing" && exit 1
 cd $SIPP_DIR
-make pcapplay_ossl
+make pcapplay_ossl 2>&1 >make.out
 [ $? -ne 0 ] && echo "ERROR: make pcapplay_ossl failed" && exit 1
 sudo cp sipp /usr/bin
 
@@ -94,7 +96,7 @@ git clone https://github.com/asterisk/pjproject pjproject >svn-co-pjproject.out
 [ $? -ne 0 ] && echo "ERROR: svn co pjproject failed" && exit 1
 cd pjproject
 [ $? -ne 0 ] && echo "ERROR: cd to pjproject failed" && exit 1
-./configure --prefix=/usr --enable-shared --disable-sound --disable-resample --disable-video --disable-opencore-amr --libdir=$SYSLIBDIR
+./configure --prefix=/usr --enable-shared --disable-sound --disable-resample --disable-video --disable-opencore-amr --libdir=$SYSLIBDIR 2>&1 >configure.out
 make dep > make-dep.out
 [ $? -ne 0 ] && echo "ERROR: make dep pjproject failed" && exit 1
 make >make.out
@@ -106,24 +108,47 @@ cd ..
 # install PJSUA
 
 rm -rf pjsua
-[ $? -ne 0 ] && echo "ERROR: rm -rf pjsua failed" && exit 1
-svn co http://svn.pjsip.org/repos/pjproject/trunk pjsua >svn-co-pjsua.out
+[ $? -ne 0 -o -d pjsua ] && echo "ERROR: rm -rf pjsua failed" && exit 1
+svn co http://svn.pjsip.org/repos/pjproject/trunk pjsua 2>&1 >svn-co-pjsua.out
 [ $? -ne 0 ] && echo "ERROR: svn co pjsua failed" && exit 1
 cd pjsua
 [ $? -ne 0 ] && echo "ERROR: cd to pjsua failed" && exit 1
-./configure CFLAGS=-fPIC
+
 echo "#define PJ_HAS_IPV6 1" >pjlib/include/pj/config_site.h
-cat pjlib/include/pj/config_site_sample.h  >>pjlib/include/pj/config_site.h
-make dep >make-dep.out
+# sandwichmaker-puppet doesn't do this...
+#cat pjlib/include/pj/config_site_sample.h  >>pjlib/include/pj/config_site.h
+
+#./configure CFLAGS=-fPIC
+./configure --enable-shared --libdir=$SYSLIBDIR --with-external-srtp --with-external-speex --with-external-pa 2>&1 >configure.out
+
+make dep 2>&1 >make-dep.out
 [ $? -ne 0 ] && echo "ERROR: make pjsua def failed" && exit 1
-make >make.out
+make 2>&1 >make.out
 [ $? -ne 0 ] && echo "ERROR: make pjsua failed" && exit 1
-make -C pjsip-apps/build pjsua  >make-pjsua.out
+make -C pjsip-apps/build pjsua  2>&1 >make-pjsua.out
 [ $? -ne 0 ] && echo "ERROR: make pjsua specifically failed" && exit 1
+sudo make install 2>&1 >make-install.out
+[ $? -ne 0 ] && echo "ERROR: make install pjsua failed" && exit 1
+
 sudo cp -v pjsip-apps/bin/pjsua-`uname -m`-*-linux-gnu /usr/sbin/pjsua
 [ $? -ne 0 ] && echo "ERROR: cp pjsua install failed" && exit 1
-sudo make -C pjsip-apps/src/python install >make-install.out
+sudo make -C pjsip-apps/src/python install 2>&1 >make-install.out
 [ $? -ne 0 ] && echo "ERROR: make pjsua python install failed" && exit 1
+
+# some files left as root
+sudo chown -R $USER.$USER .
+
+# reinstall libraries with different configuration options (per puppet)
+./configure --enable-shared --libdir=$SYSLIBDIR --with-external-srtp --with-external-speex --with-external-pa --disable-resample 2>&1 >configure2.out
+
+make dep 2>&1 > make-dep2.out
+[ $? -ne 0 ] && echo "ERROR: make dep pjsua2 failed" && exit 1
+make 2>&1 > make-pjsua2.out
+[ $? -ne 0 ] && echo "ERROR: make pjsua2 failed" && exit 1
+sudo make install 2>&1 >make-install2.out
+[ $? -ne 0 ] && echo "ERROR: make install pjsua2 failed" && exit 1
+sudo ldconfig
+
 
 # some files left as root
 sudo chown -R $USER.$USER .
